[toc]

## async/await 内部捕获错误

使用 try...catch 语句

```
async function foo() {
	try {
		const test = await Promise.reject(2);
		// 下面这行不会执行
		console.log('I'm not gonna be printed');
	} catch (err) {
		console.log(err); //2
	}
}
foo();
```

如果在外部捕获，使用：

```
async function foo(){
    const test = await Promise.reject(2);
    console.log('I'm not gonna be printed');
}
foo().catch(err => console.log(err)) //2
```

如果不捕获错误（不使用 catch 语句），则会在控制台 throw 一个`UnhandledPromiseRejectionWarning: 2`

## 后端跳转路由

在后端写路由的时候，不能使用`res.redirect(url)`之类的路由跳转语句，因为语句中的 url 对应的是后端服务器的域

比如前端的域为`http://localhost:8080`，后端为`http://localhost:3000`，用上面那个语句将会跳转到`http://localhost:3000/${url}`(如果这个路由有 BASE_URL 的话，还要在 url 前加上 BASE_URL)

而这个项目使用前端控制路由跳转

## 为什么在 passport 中设置 failureFlash 会报错

[here's why](https://stackoverflow.com/questions/54188190/error-no-default-engine-was-specified-and-no-extension-was-provided-in-node-ser)

and for details:

[代码中没有设置 view engine，比如 jade](https://stackoverflow.com/questions/23595282/error-no-default-engine-was-specified-and-no-extension-was-provided/23596000)

也就是说不能使用`res.render`，因为后端没有提供渲染视图的引擎（非服务器渲染）

## passport local 策略不适合前端路由！！！

前端路由应该做`passport-jwt`，生成 token 并在前端 axios 拦截器中使用
